DROP INDEX idx_ingredients_object_name;
CREATE UNIQUE INDEX idx_ingredients_object_name ON Ingredients (object_name);

INSERT INTO Ingredients (object_name, category) VALUES ('roast beef', 'Meat');
INSERT INTO Ingredients (object_name, category) VALUES ('corned beef', 'Meat');
INSERT INTO Ingredients (object_name, category) VALUES ('onion', 'Vegetable');
INSERT INTO Ingredients (object_name, category) VALUES ('pickles', 'Condiment');
INSERT INTO Ingredients (object_name, category) VALUES ('ketchup', 'Condiment');
INSERT INTO Ingredients (object_name, category) VALUES ('cheese', 'Cheese');
INSERT INTO Ingredients (object_name, category) VALUES ('avocado', 'Fruit');
INSERT INTO Ingredients (object_name, category) VALUES ('egg', 'Protein');
INSERT INTO Ingredients (object_name, category) VALUES ('hummus', 'Spread');
INSERT INTO Ingredients (object_name, category) VALUES ('tomato', 'Vegetable');
INSERT INTO Ingredients (object_name, category) VALUES ('tuna', 'Seafood');
INSERT INTO Ingredients (object_name, category) VALUES ('bologna', 'Meat');
INSERT INTO Ingredients (object_name, category) VALUES ('grape jelly', 'Spread');
INSERT INTO Ingredients (object_name, category) VALUES ('peanut butter', 'Spread');
INSERT INTO Ingredients (object_name, category) VALUES ('salmon', 'Seafood');
INSERT INTO Ingredients (object_name, category) VALUES ('bacon', 'Meat');
INSERT INTO Ingredients (object_name, category) VALUES ('mayonnaise', 'Condiment');
INSERT INTO Ingredients (object_name, category) VALUES ('sunflower seeds', 'Seed');
INSERT INTO Ingredients (object_name, category) VALUES ('poppy seeds', 'Seed');
INSERT INTO Ingredients (object_name, category) VALUES ('pumpkin seeds', 'Seed');
INSERT INTO Ingredients (object_name, category) VALUES ('lettuce', 'Vegetable');
INSERT INTO Ingredients (object_name, category) VALUES ('anchovy paste', 'Condiment');
INSERT INTO Ingredients (object_name, category) VALUES ('ham', 'Meat');
INSERT INTO Ingredients (object_name, category) VALUES ('turkey ham', 'Meat');
INSERT INTO Ingredients (object_name, category) VALUES ('chicken ham', 'Meat');
INSERT INTO Ingredients (object_name, category) VALUES ('basil', 'Herb');
INSERT INTO Ingredients (object_name, category) VALUES ('dill', 'Herb');
INSERT INTO Ingredients (object_name, category) VALUES ('shrimp', 'Seafood');
INSERT INTO Ingredients (object_name, category) VALUES ('crab', 'Seafood');
INSERT INTO Ingredients (object_name, category) VALUES ('banana', 'Fruit');
INSERT INTO Ingredients (object_name, category) VALUES ('cheddar', 'Cheese');
INSERT INTO Ingredients (object_name, category) VALUES ('gouda', 'Cheese');
INSERT INTO Ingredients (object_name, category) VALUES ('roquefort', 'Cheese');
INSERT INTO Ingredients (object_name, category) VALUES ('blue cheese', 'Cheese');
INSERT INTO Ingredients (object_name, category) VALUES ('cream cheese', 'Cheese');
INSERT INTO Ingredients (object_name, category) VALUES ('mustard', 'Condiment');
INSERT INTO Ingredients (object_name, category) VALUES ('mustard seeds', 'Seed');
INSERT INTO Ingredients (object_name, category) VALUES ('jalapenos', 'Pepper');
INSERT INTO Ingredients (object_name, category) VALUES ('chili sauce', 'Condiment');
INSERT INTO Ingredients (object_name, category) VALUES ('butter', 'Dairy');
INSERT INTO Ingredients (object_name, category) VALUES ('salted butter', 'Dairy');
INSERT INTO Ingredients (object_name, category) VALUES ('swiss cheese', 'Cheese');
INSERT INTO Ingredients (object_name, category) VALUES ('capers', 'Condiment');
INSERT INTO Ingredients (object_name, category) VALUES ('cornichons', 'Condiment');
INSERT INTO Ingredients (object_name, category) VALUES ('bechamel sauce', 'Sauce');